src/Entity/OrderItem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\OrderItemRepository;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="`order_items`")
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Product::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual(1)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     * @ORM\JoinColumn(nullable=false)
     */
    private $order;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;
        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getOrder(): ?Order
    {
        return $this->order;
    }

    public function setOrder(?Order $order): self
    {
        $this->order = $order;
        return $this;
    }

    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }
    
    public function getTotal(): float
    {
        return $this->getProduct()->getPrice() * $this->getQuantity();
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\RemoveCartItemListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])

            ->add('saveCart', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])

            ->add('clearCart', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-danger'
                ]
            ]);

        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
            'csrf_protection' => false,
        ]);
    }
}

src/Controller/CartController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="app_cart", methods={"GET", "POST"})
     */
    public function index(Request $request, CartManager $cartManager): Response
    {
        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdated(new \DateTime('NOW'));
            $cartManager->save($cart);

            $this->addFlash('success', 'Cart updated!');
            return $this->redirectToRoute('app_cart');
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ __app_name__ }} - Cart{% endblock %}
{% block body %}
    {% if cart.items.count > 0 %}
        <h1 class="h3 my-4">Shopping Cart</h1>
        <div class="row">
            <div class="col-md-8">
                <table class="table bg-light rounded table-borderless border shadow">
                    <thead class="border">
                        <tr>
                          <th class="font-weight-normal" scope="col">#</th>
                          <th class="font-weight-normal" scope="col">Name</th>
                          <th class="font-weight-normal" scope="col">Price</th>
                          <th class="font-weight-normal" scope="col">Quantity</th>
                          <th class="font-weight-normal" scope="col">Action</th>
                        </tr>
                    </thead>
                    {{ form_start(form) }}
                        {% for item in form.items %}
                            <tbody>
                                <tr>
                                    <td><img src="https://picsum.photos/id/119/200/150" width="64" alt="Product image"></td>
                                    <th><a href="{{ path('app_product_show', {'id': item.vars.data.product.id}) }}">{{ item.vars.data.product.name }}</a></th>
                                    <td>$ {{ item.vars.data.product.price }}</td>
                                    <td>
                                        {{ form_widget(item.quantity, {
                                            'attr': {
                                                'class': 'form-control form-control-sm quantity-input' ~ (item.quantity.vars.valid ? '' : 'is-invalid'),
                                            }
                                        }) }}

                                        <div class="invalid-feedback">
                                            {{ form_errors(item.quantity) }}
                                        </div>
                                    </td>
                                    <td>{{ form_widget(item.remove, {'attr': {'class': 'btn btn-danger btn-sm'}}) }}</td>
                                </tr>
                            </tbody>
                        {% endfor %}
                    </table>

                    <div class="float-right">
                        {{ form_widget(form.saveCart) }}
                        {{ form_widget(form.clearCart) }}
                    </div>
                {{ form_end(form, {'render_rest': false}) }}
            </div>

            <div class="col-md-4">
                <div class="p-3 bg-light rounded border shadow">
                    <h5>Cart Total</h5>
                    
                    <hr class="my-4">
                    
                    <p>Subtotal <span class="float-right">$ {{ cart.total }}</span></p>
                    <p>Delivery <span class="float-right">*free</span></p>
                    <p>Total <span class="float-right">$ {{ cart.total }}</span></p>
                    
                    <hr class="my-4">

                    <a href="#" class="btn btn-warning w-100">Checkout</a>
                </div>
            </div>
        </div>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}
{% endblock %}